version: '3.6'

services: 
  #postgres db for local development
  f1.postgres-database:
    image: postgres:14.1
    environment:
      POSTGRES_USER: "api"
      POSTGRES_PASSWORD: "api"
    ports:
        - "5432:5432"